version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-184-73-192-172.compute-1.amazonaws.com
            database: devc84acha0aes
            user: lgmdkjplnjeatx
            password: 92a77e0488099b0427fa542954a7cb14b6e728b77f19ec0134af75cc5a7f5cb3
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true